//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_2.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int question_number { get; set; }
        public System.Guid person_ID { get; set; }
        public System.DateTime answer_time { get; set; }
        public string answer__text { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Question Question { get; set; }
    }
}
